'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, FileText, ShieldAlert } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        
        {/* Header */}
        <div className="mb-8">
          <Link href="/" className="inline-flex items-center text-gray-500 hover:text-blue-700 transition-colors mb-6">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
          </Link>
          <div className="flex items-center gap-3">
            <div className="p-3 bg-blue-100 text-blue-700 rounded-lg">
                <FileText className="w-8 h-8" />
            </div>
            <div>
                <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
                <p className="text-gray-500 text-sm">Last Updated: December 13, 2025</p>
            </div>
          </div>
        </div>

        {/* Content Card */}
        <div className="bg-white shadow-sm border border-gray-200 rounded-2xl p-8 md:p-12 text-gray-700 leading-relaxed">
            
          <section className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing or using the <strong>Smart Citizen LK</strong> platform ("Service"), you agree to be bound by these Terms of Service. This platform is owned and operated by the Government of Sri Lanka. If you do not agree to these terms, you must strictly not use this Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">2. Eligibility & Registration</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must be a citizen of Sri Lanka with a valid National Identity Card (NIC).</li>
              <li>You must be at least 16 years of age to manage your own account independently.</li>
              <li>You agree to provide accurate, current, and complete information during the registration process.</li>
              <li><strong>Strict Warning:</strong> Impersonating another individual or using a fake NIC number is a criminal offense under the Computer Crimes Act of Sri Lanka.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">3. User Responsibilities</h2>
            <p className="mb-4">
              You are responsible for maintaining the confidentiality of your account password and OTPs. You agree to notify the Help Desk (1919) immediately of any unauthorized use of your account.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">4. Digital Documents & Verification</h2>
            <p className="mb-4">
              Documents issued through this platform (Birth Certificates, Police Reports, etc.) are digitally signed and legally valid under the Electronic Transactions Act.
            </p>
            <p>
              Tampering with a digital certificate or QR code generated by this system is a punishable offense.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">5. Limitation of Liability</h2>
            <p className="mb-4">
              While the Government strives for 99.9% uptime, we are not liable for any delays in service processing caused by technical failures, third-party payment gateway errors, or force majeure events.
            </p>
          </section>

          <div className="border-t border-gray-100 pt-8 mt-8">
            <p className="text-sm text-gray-500">
              For legal inquiries, please contact: <br />
              <span className="font-semibold text-gray-900">Legal Division, Presidential Secretariat, Colombo 01.</span>
            </p>
          </div>

        </div>
      </div>
    </div>
  );
}